version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: victorgendel/flaskapp:v1
    container_name: my-flask-application
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./Scores:/app/Scores
    command: ["python3", "Main_Game.py"]
    restart: always
